// <auto-generated />
namespace GUI_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class complainfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(complainfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202112032157469_complainfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
